### PR TITLE
Allow running the code from this repo even while copies of these classes still exist in the allennlp repo

### PR DESCRIPTION
**Pull request by dirkgr**
This is a temporary measure until we have completed moving everything into this repo.

### CODE REVIEW

**Comment by matt-gardner** [comment]
I'm not strictly opposed to this, but can we just remove everything from the main repo now, instead?

**Comment by matt-gardner** [comment]
I have an open PR to do that.

**Comment by dirkgr** [comment]
Sure, let's do it. The earlier the better.

**Comment by dirkgr** [comment]
https://github.com/allenai/allennlp/pull/3348

**Comment by dirkgr** [comment]
That's a non-trivial merge, so I want to finish this first before fixing allenai/allennlp#3348.

**Comment by dirkgr** [comment]
We don't need this anymore, now that #11 is merged.

**Pull request closed without merging**
